// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/pb/messages.proto

package protocols_messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageData struct {
	ClientVersion        string   `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Gossip               bool     `protobuf:"varint,4,opt,name=gossip,proto3" json:"gossip,omitempty"`
	NodeID               string   `protobuf:"bytes,5,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	NodePubKey           []byte   `protobuf:"bytes,6,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e4c5a068edfb1e, []int{0}
}

func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

func (m *MessageData) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *MessageData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *MessageData) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageData)(nil), "protocols.messages.MessageData")
}

func init() { proto.RegisterFile("server/pb/messages.proto", fileDescriptor_d2e4c5a068edfb1e) }

var fileDescriptor_d2e4c5a068edfb1e = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xbf, 0x4a, 0x04, 0x31,
	0x10, 0xc6, 0xc9, 0xde, 0xb9, 0x7a, 0xe3, 0x9f, 0x62, 0x0a, 0x99, 0x42, 0x24, 0x88, 0x45, 0xaa,
	0xbb, 0xc2, 0x57, 0xb8, 0x46, 0x44, 0x90, 0x14, 0xf6, 0xd9, 0xdd, 0x61, 0x09, 0xec, 0x26, 0x21,
	0x13, 0x05, 0x1f, 0xd0, 0xf7, 0x92, 0x8d, 0x2b, 0x6a, 0x35, 0xdf, 0xef, 0xf7, 0xcd, 0x14, 0x03,
	0x24, 0x9c, 0xdf, 0x39, 0x1f, 0x52, 0x77, 0x98, 0x59, 0xc4, 0x8d, 0x2c, 0xfb, 0x94, 0x63, 0x89,
	0x88, 0x75, 0xf4, 0x71, 0x92, 0xfd, 0x4f, 0x73, 0xf7, 0xa9, 0xe0, 0xfc, 0xf9, 0x1b, 0x8e, 0xae,
	0x38, 0xbc, 0x87, 0xcb, 0x7e, 0xf2, 0x1c, 0xca, 0x2b, 0x67, 0xf1, 0x31, 0x90, 0xd2, 0xca, 0xec,
	0xec, 0x7f, 0x89, 0x37, 0xb0, 0x2b, 0x7e, 0x66, 0x29, 0x6e, 0x4e, 0xd4, 0x68, 0x65, 0x36, 0xf6,
	0x57, 0xe0, 0x15, 0x34, 0x7e, 0xa0, 0x4d, 0x3d, 0x6c, 0xfc, 0x80, 0xd7, 0xd0, 0x8e, 0x51, 0xc4,
	0x27, 0xda, 0x6a, 0x65, 0xce, 0xec, 0x4a, 0x8b, 0x0f, 0x71, 0xe0, 0xc7, 0x23, 0x9d, 0xd4, 0xdd,
	0x95, 0xf0, 0x16, 0x60, 0x49, 0x2f, 0x6f, 0xdd, 0x13, 0x7f, 0x50, 0xab, 0x95, 0xb9, 0xb0, 0x7f,
	0x0c, 0x22, 0x6c, 0xc5, 0x8f, 0x81, 0x4e, 0x6b, 0x53, 0x73, 0xd7, 0xd6, 0xdf, 0x1e, 0xbe, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xd1, 0xbc, 0x4f, 0xfa, 0xfe, 0x00, 0x00, 0x00,
}
